name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2        
      - name: Install dependencies
        run: |
          npm install
          export NODE_OPTIONS=--openssl-legacy-provider
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_PAGES_TOKEN }}
          deploy-branch: master
          gatsby-args: --prefix-paths && gh-pages -d public