name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "sitbne@gmail.com"
          git config --global user.name "sitbne"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2        
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run deploy:ci