name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

jobs:
  DeployToGithubPages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2        
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          git remote set-url origin https://git:${GH_PAGES_TOKEN}@github.com/sitbne/sitbne.github.io.git
          npx gh-pages -d public -u "github-actions-bot <support+actions@github.com>" -b master
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}